version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: web-app-bookmarks
    command: ./entrypoint.sh
#    volumes:
#      - ./app:/home/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
  db:
    image: postgres:14-alpine
    container_name: db-postgres-bookmarks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

  redis:
    container_name: redis-bookmarks
    ports:
      - "6379:6379"
    image: redis

  worker:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: worker-bookmarks
    command: poetry run celery -A config worker -l INFO
    depends_on:
      - web-app
    env_file:
      - .env

  flower:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: flower-bookmarks
    command: poetry run celery -A config flower
    depends_on:
      - worker
    ports:
      - "5555:5555"
    env_file:
      - .env

volumes:
  postgres_data:
