version: "3.9"

services:
  web-app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    container_name: web-app-bookmarks
    command: ./entrypoint.sh
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:14-alpine
    container_name: db-postgres-bookmarks
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


volumes:
  postgres_data:
