# Generated by Django 4.2.6 on 2023-10-28 16:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("bookmarks_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="bookmark_url",
            field=models.URLField(verbose_name="Ссылка"),
        ),
        migrations.AlterUniqueTogether(
            name="bookmark",
            unique_together={("user", "bookmark_url")},
        ),
    ]
