# Generated by Django 4.2.6 on 2023-10-31 18:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks_app", "0002_alter_bookmark_bookmark_url_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="bookmark",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Закладка",
                "verbose_name_plural": "Закладки",
            },
        ),
    ]
