# Generated by Django 4.2.6 on 2023-11-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks_app", "0003_alter_bookmark_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="statys",
            field=models.CharField(
                choices=[
                    ("Planned", "Заплонировано"),
                    ("Executed", "Выполняется"),
                    ("Done", "Выполнено"),
                    ("Error", "Ошибка"),
                ],
                default="Planned",
                max_length=32,
                verbose_name="Статус",
            ),
        ),
    ]
