# Generated by Django 4.2.6 on 2023-11-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks_app", "0003_alter_bookmark_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="statys",
            field=models.CharField(
                choices=[
                    ("Заплонировано", "Planned"),
                    ("Выполняется", "Executed"),
                    ("Выполнено", "Done"),
                    ("Ошибка", "Error"),
                ],
                default="Заплонировано",
                verbose_name="Статус",
            ),
        ),
    ]
