# Generated by Django 4.2.6 on 2023-11-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookmarks_app", "0004_bookmark_statys"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookmark",
            name="statys",
            field=models.CharField(
                choices=[
                    ("Planned", "Заплонировано"),
                    ("Executed", "Выполняется"),
                    ("Done", "Выполнено"),
                    ("Error", "Ошибка"),
                ],
                default="Planned",
                verbose_name="Статус",
            ),
        ),
    ]
